### ISSUE TITLE
`codecs.load_all_yaml(...)` doesn't handle objects that are of kind `*List`

### ISSUE THREAD

**Issue by addyess** [gtsystem/lightkube#50]
given a file like this defined by [ServiceAccountList](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/#ServiceAccountList)

```yaml
apiVersion: v1
kind: ServiceAccountList
metadata: {}
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: test-sa
    namespace: kube-system
```

can't be handled by `codecs.load_all_yaml(...)` 

I think i could patch something pretty simply to read through the items of the list and they'd be parsed just fine.  I'll likely raise a PR for this.
